### ISSUE TITLE
Allow for multiple sizes as an option / make it easier to see larger groups of people

### ISSUE THREAD

**Issue by simensen** [alisdair/team-time-zone#5]
I'm only able to see at most 4 people from any given timezone. It would be great if we could have the option of hiding the image or make it possible to have a smaller image shown. For example, if the image was ~1/4 the size with the username + full name to the right of it. Or if the image could be 1/8 the size with either the username or the full name shown.

Neat tool. :)

![image](https://cloud.githubusercontent.com/assets/191200/12274865/89266cd4-b932-11e5-93e4-b096a09e0bff.png)

**Comment by simensen** [comment]
Oh! It should be worth noting that there are at least two people missing from that right column. Granted, *everyone else* is in that TZ except for me. Still, it would be nice to use this for larger teams that have their timezones spread out more.

**Comment by alisdair** [comment]
I don't want to add options, but I would accept a PR which uses max

**Comment by alisdair** [comment]
Sorry, misclick :cold_sweat: 

I'm working on a fix now to add vertically responsive user images using max-height. Thanks for the issue report!

**Comment by alisdair** [comment]
![vertically-responsive](https://cloud.githubusercontent.com/assets/68917/12278235/e5383f12-b977-11e5-9f35-d4e1fd03b61c.gif)

Hope this helps. In production now.

**Comment by simensen** [comment]
Yes, this is an interesting start. It is funny though because for me in my environment at browser full screen I get the exact same view. I only get smaller icons if I make my browser window shorter.

https://www.dropbox.com/s/11go97x5kkx7bds/teamtimezone.mp4?dl=0

**Comment by simensen** [comment]
Either way, I appreciate that you don't want to make options. :) It's still awesome and I'll still probably use it for now even as-is! Thanks for the quick feedback!
